export * from './user.interface';
export * from './post.interface';
export * from './comment.interface';
export * from './comment-details.interface';
export * from './address.interface';
export * from './company.interface';
export * from './geo.interface';
export * from './user-details.interface';
export * from './post-details.interface';
